const NEW_REGS = [
  {
    "centre": "Bolton",
    "display": "Bolton",
    "cda": "North CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 24,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 12,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 69,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 105,
    "to_go": 105,
    "per_week": 8,
    "regs_v_target": 0.0
  },
  {
    "centre": "Bury",
    "display": "Bury",
    "cda": "North CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 19,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 11,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 47,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 77,
    "to_go": 77,
    "per_week": 6,
    "regs_v_target": 0.0
  },
  {
    "centre": "Rochdale",
    "display": "Rochdale",
    "cda": "North CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 19,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 11,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 55,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 85,
    "to_go": 85,
    "per_week": 7,
    "regs_v_target": 0.0
  },
  {
    "centre": "SQ",
    "display": "Salford Quays",
    "cda": "North CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 32,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 18,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 90,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 140,
    "to_go": 140,
    "per_week": 11,
    "regs_v_target": 0.0
  },
  {
    "centre": "NORTH CDA",
    "display": "NORTH CDA",
    "cda": "North CDA",
    "type": "cda",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 94,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 52,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 261,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 407,
    "to_go": 407,
    "per_week": 32,
    "regs_v_target": 0.0
  },
  {
    "centre": "Bradford",
    "display": "Bradford",
    "cda": "WY CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 22,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 13,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 70,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 105,
    "to_go": 105,
    "per_week": 8,
    "regs_v_target": 0.0
  },
  {
    "centre": "Huddersfield",
    "display": "Huddersfield",
    "cda": "WY CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 23,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 13,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 72,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 108,
    "to_go": 108,
    "per_week": 9,
    "regs_v_target": 0.0
  },
  {
    "centre": "Silsden",
    "display": "Silsden",
    "cda": "WY CDA",
    "type": "centre",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 8,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 3,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 23,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 34,
    "to_go": 34,
    "per_week": 3,
    "regs_v_target": 0.0
  },
  {
    "centre": "WY CDA",
    "display": "WY CDA",
    "cda": "WY CDA",
    "type": "cda",
    "jul_counting": 0,
    "jul_clcp": 0,
    "jul_fleet": 0,
    "jul_total": 0,
    "jul_target": 53,
    "aug_counting": 0,
    "aug_clcp": 0,
    "aug_fleet": 0,
    "aug_total": 0,
    "aug_target": 29,
    "sep_counting": 0,
    "sep_clcp": 0,
    "sep_fleet": 0,
    "sep_total": 0,
    "sep_target": 165,
    "total_counting": 0,
    "total_fleet": 0,
    "total_regs": 0,
    "qtr_target": 247,
    "to_go": 247,
    "per_week": 20,
    "regs_v_target": 0.0
  },
  {
    "centre": "GROUP TOTAL",
    "display": "Group Total",
    "cda": "Group",
    "type": "total",
    "jul_total": 0,
    "jul_target": 147,
    "aug_total": 0,
    "aug_target": 81,
    "sep_total": 0,
    "sep_target": 426,
    "total_regs": 0,
    "qtr_target": 654,
    "to_go": 654,
    "per_week": 52,
    "total_counting": 0,
    "total_fleet": 0,
    "regs_v_target": 0.0
  }
];
const USED = [
  {
    "centre": "Bolton",
    "display": "Bolton",
    "cda": "North CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 63,
    "aug_used": 0,
    "aug_target": 62,
    "sep_used": 0,
    "sep_target": 62,
    "total_used": 0,
    "qtr_target": 187
  },
  {
    "centre": "Bury",
    "display": "Bury",
    "cda": "North CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 55,
    "aug_used": 0,
    "aug_target": 54,
    "sep_used": 0,
    "sep_target": 54,
    "total_used": 0,
    "qtr_target": 163
  },
  {
    "centre": "Rochdale",
    "display": "Rochdale",
    "cda": "North CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 51,
    "aug_used": 0,
    "aug_target": 50,
    "sep_used": 0,
    "sep_target": 50,
    "total_used": 0,
    "qtr_target": 151
  },
  {
    "centre": "SQ",
    "display": "Salford Quays",
    "cda": "North CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 60,
    "aug_used": 0,
    "aug_target": 59,
    "sep_used": 0,
    "sep_target": 59,
    "total_used": 0,
    "qtr_target": 178
  },
  {
    "centre": "NORTH CDA",
    "display": "NORTH CDA",
    "cda": "North CDA",
    "type": "cda",
    "jul_used": 0,
    "jul_target": 229,
    "aug_used": 0,
    "aug_target": 225,
    "sep_used": 0,
    "sep_target": 225,
    "total_used": 0,
    "qtr_target": 679
  },
  {
    "centre": "Bradford",
    "display": "Bradford",
    "cda": "WY CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 36,
    "aug_used": 0,
    "aug_target": 36,
    "sep_used": 0,
    "sep_target": 36,
    "total_used": 0,
    "qtr_target": 108
  },
  {
    "centre": "Huddersfield",
    "display": "Huddersfield",
    "cda": "WY CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 47,
    "aug_used": 0,
    "aug_target": 46,
    "sep_used": 0,
    "sep_target": 46,
    "total_used": 0,
    "qtr_target": 139
  },
  {
    "centre": "Silsden",
    "display": "Silsden",
    "cda": "WY CDA",
    "type": "centre",
    "jul_used": 0,
    "jul_target": 22,
    "aug_used": 0,
    "aug_target": 21,
    "sep_used": 0,
    "sep_target": 21,
    "total_used": 0,
    "qtr_target": 64
  },
  {
    "centre": "WY CDA",
    "display": "WY CDA",
    "cda": "WY CDA",
    "type": "cda",
    "jul_used": 0,
    "jul_target": 105,
    "aug_used": 0,
    "aug_target": 103,
    "sep_used": 0,
    "sep_target": 103,
    "total_used": 0,
    "qtr_target": 311
  }
];
const FLEET_BCH = [
  {
    "centre": "Bolton",
    "display": "Bolton",
    "cda": "North CDA",
    "type": "centre",
    "q3_regs": 0,
    "target": 7,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "Bury",
    "display": "Bury",
    "cda": "North CDA",
    "type": "centre",
    "q3_regs": 0,
    "target": 5,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "Rochdale",
    "display": "Rochdale",
    "cda": "North CDA",
    "type": "centre",
    "q3_regs": 0,
    "target": 6,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "SQ",
    "display": "Salford Quays",
    "cda": "North CDA",
    "type": "centre",
    "q3_regs": 0,
    "target": 8,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "NORTH CDA",
    "display": "NORTH CDA",
    "cda": "North CDA",
    "type": "cda",
    "q3_regs": 0,
    "target": 26,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "Bradford",
    "display": "Bradford",
    "cda": "WY CDA",
    "type": "centre",
    "q3_regs": 1,
    "target": 6,
    "pct": 16.7,
    "active_orders": 9
  },
  {
    "centre": "Huddersfield",
    "display": "Huddersfield",
    "cda": "WY CDA",
    "type": "centre",
    "q3_regs": 0,
    "target": 7,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "Silsden",
    "display": "Silsden",
    "cda": "WY CDA",
    "type": "centre",
    "q3_regs": 0,
    "target": 2,
    "pct": 0,
    "active_orders": 0
  },
  {
    "centre": "WY CDA",
    "display": "WY CDA",
    "cda": "WY CDA",
    "type": "cda",
    "q3_regs": 1,
    "target": 15,
    "pct": 6.7,
    "active_orders": 9
  }
];
